### ISSUE TITLE
如何删除独显缓冲帧

### ISSUE THREAD

**Issue by xuchaoa** [gngpp/Asus-ROG-Strix-B460I_OC_Hackintosh#4]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/34988066/205576913-8b5cc467-15e3-4451-a0cf-4c33b0cffa7c.png">
你好，我只有核显，请问独显缓冲帧在哪删除？是 `config.plist` 中的 `framebuffer` 吗？ 具体是哪个字段呢

**Comment by 0x676e67** [comment]
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/34988066/205576913-8b5cc467-15e3-4451-a0cf-4c33b0cffa7c.png">
> 
> 你好，我只有核显，请问独显缓冲帧在哪删除？是 `config.plist` 中的 `framebuffer` 吗？ 具体是哪个字段呢

忘记了，可以使用opencore configurator这个工具去删

**Comment by 0x676e67** [comment]
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/34988066/205576913-8b5cc467-15e3-4451-a0cf-4c33b0cffa7c.png">
> 
> 你好，我只有核显，请问独显缓冲帧在哪删除？是 `config.plist` 中的 `framebuffer` 吗？ 具体是哪个字段呢

不删也没什么事，不影响

**Comment by xuchaoa** [comment]
好的，感谢解答
