### ISSUE TITLE
请问使用的具体网卡是？

### ISSUE THREAD

**Issue by xuchaoa** [gngpp/Asus-ROG-Strix-B460I_OC_Hackintosh#5]
买了一个联想版本的 dw1560, wifi正常驱动，蓝牙可以开关但是没法连接蓝牙耳机，看了一下蓝牙的固件上传应该有问题，请问有什么解决方法？ 顺便问一下作者用的具体什么网卡，我也整一个

<img width="300" alt="image" src="https://user-images.githubusercontent.com/34988066/210088747-56dc4bbb-31ad-4559-971b-640397b6ab2e.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/34988066/210089001-66e655eb-c5fe-4bb2-ac5f-42b81a9bdb9f.png">

**Comment by 0x676e67** [comment]
> 买了一个联想版本的 dw1560, wifi正常驱动，蓝牙可以开关但是没法连接蓝牙耳机，看了一下蓝牙的固件上传应该有问题，请问有什么解决方法？ 顺便问一下作者用的具体什么网卡，我也整一个
> 
> <img alt="image" width="300" src="https://user-images.githubusercontent.com/34988066/210088747-56dc4bbb-31ad-4559-971b-640397b6ab2e.png">
> 
> <img alt="image" width="388" src="https://user-images.githubusercontent.com/34988066/210089001-66e655eb-c5fe-4bb2-ac5f-42b81a9bdb9f.png">

我之前也是用dw1560，毛病很多，只有在windows下是正常的。想完美只有换白果卡

**Comment by xuchaoa** [comment]
感谢解答
